version: '3.7'

services:
  react-portfolio:
    container_name: react-portfolio
    build: .
    volumes:
      - './src:/src'
      - ./public/assets:/public/assets
      - ./public/images:/public/images
      - /node_modules
    ports:
      - 80:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
