# version: '3.7'

# services:
#   react-portfolio:
#     container_name: react-portfolio
#     build: .
#     volumes:
#       - './src:/src'
#       - ./public/assets:/public/assets
#       - ./public/images:/public/images
#       - /node_modules
#     ports:
#       - 80:3000
#     stdin_open: true
#     restart: 'unless-stopped'
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     command: npm start

version: '3'

services:
  react-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-portfolio
    container_name: react-portfolio
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - react-portfolio
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email adam@adamsackfield.uk --agree-tos --no-eff-email --staging -d adamsackfield.uk  -d www.adamsackfield.uk

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/chopin/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge
