name: ci

on:
  push:
    branches:
    - "main"
    
jobs:
 build-debs:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Deploy Site to DigitalOcean
        uses: appleboy/ssh-action@master
        env: 
          GITHUB_USERNAME: adampaulsackfield
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            cd /home/chopin/portfolio
            git pull
            npm i
            npm run build --if-present
            \cp -r build/* /var/www/adamsackfield.uk/html/
            sudo systemctl restart nginx
          
          
          
